#!/bin/bash
# setup-dev.sh
# Configures environment for INDIVIDUAL DEVELOPER (Development Mode)

set -e
INFRA_DIR="$(dirname "$0")/../infra"
CLIENT_DIR="$(dirname "$0")/../client"
INFRA_ENV_FILE="$INFRA_DIR/.env"

echo "=========================================="
echo "Neighborly SETUP: DEVELOPMENT MODE"
echo "=========================================="
echo "This will configure your environment for a specific developer."
echo ""

# Defaults
if [ -f "$INFRA_ENV_FILE" ]; then
  DEFAULT_DEV=$(grep "^DEVELOPER_NAME=" "$INFRA_ENV_FILE" | cut -d= -f2-)
  DEFAULT_ACC=$(grep "^AWS_ACCOUNT_ID=" "$INFRA_ENV_FILE" | cut -d= -f2-)
  DEFAULT_REG=$(grep "^AWS_REGION=" "$INFRA_ENV_FILE" | cut -d= -f2-)
  DEFAULT_PRE=$(grep "^RESOURCE_PREFIX=" "$INFRA_ENV_FILE" | cut -d= -f2-)
fi
[ -z "$DEFAULT_PRE" ] && DEFAULT_PRE="neighborly"
[ -z "$DEFAULT_REG" ] && DEFAULT_REG="us-east-1"

# 1. Developer Name (REQUIRED)
read -p "Enter Developer Name (e.g. jiahao) [${DEFAULT_DEV}]: " INPUT_DEV
DEV_NAME=${INPUT_DEV:-$DEFAULT_DEV}
if [ -z "$DEV_NAME" ]; then echo "Error: Developer Name required for Dev Mode."; exit 1; fi

# 2. AWS Config
read -p "Enter AWS Account ID [${DEFAULT_ACC}]: " INPUT_ACC
AWS_ACC=${INPUT_ACC:-$DEFAULT_ACC}
if [ -z "$AWS_ACC" ]; then echo "Error: Account ID required."; exit 1; fi

read -p "Enter AWS Region [${DEFAULT_REG}]: " INPUT_REG
AWS_REG=${INPUT_REG:-$DEFAULT_REG}

read -p "Enter Base Resource Prefix [${DEFAULT_PRE}]: " INPUT_PRE
RES_PRE=${INPUT_PRE:-$DEFAULT_PRE}

# 3. Fetch Outputs (if stacks exist)
# Logic: {DeveloperName}-{ResourcePrefix}-{StackName}
FULL_PREFIX="${DEV_NAME}-${RES_PRE}"
STACK_NAME="${FULL_PREFIX}-AuthStack"

echo ""
echo "Attempting to fetch outputs from stack: ${STACK_NAME}..."

API_URL=""
API_KEY=""
USER_POOL=""
CLIENT_ID=""

if aws cloudformation describe-stacks --stack-name "$STACK_NAME" >/dev/null 2>&1; then
  API_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' --output text)
  API_KEY=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs[?OutputKey==`ApiKey`].OutputValue' --output text)
  USER_POOL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs[?OutputKey==`AuthUserPoolIdC0605E59`].OutputValue' --output text)
  CLIENT_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs[?OutputKey==`AuthUserPoolClientId8216BF9A`].OutputValue' --output text)
  echo "✓ Stack found. Retrieved outputs."
else
  echo "⚠️  Stack '${STACK_NAME}' not found."
  echo "   (Outputs will be empty in .env. Run './scripts/deploy-dev.sh AuthStack' then run this script again.)"
fi

# 4. Write infra/.env (Always write full structure)
echo "Writing infra/.env..."
cat > "$INFRA_ENV_FILE" << EOF
# Auto-generated by setup-dev.sh
AWS_ACCOUNT_ID=${AWS_ACC}
AWS_REGION=${AWS_REG}
RESOURCE_PREFIX=${RES_PRE}
DEVELOPER_NAME=${DEV_NAME}

# Cognito User Pool
USER_POOL_ID=${USER_POOL}
USER_POOL_CLIENT_ID=${CLIENT_ID}

# AppSync API
APPSYNC_URL=${API_URL}
API_KEY=${API_KEY}
EOF

# 5. Write client/.env.local
echo "Writing client/.env.local..."
cat > "$CLIENT_DIR/.env.local" << EOF
# Auto-generated by setup-dev.sh
EXPO_PUBLIC_APPSYNC_URL=${API_URL}
EXPO_PUBLIC_API_KEY=${API_KEY}
EXPO_PUBLIC_AWS_REGION=${AWS_REG}
EXPO_PUBLIC_USER_POOL_ID=${USER_POOL}
EXPO_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}
EOF

echo ""
echo "✅ Dev Setup Complete"
