#!/bin/bash
# Auto-update environment variables after CDK deployment
# Usage: ./update-env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$PROJECT_ROOT/infra"
CLIENT_DIR="$PROJECT_ROOT/client"

echo "=========================================="
echo "Updating Environment Variables"
echo "=========================================="
echo ""

echo "→ Detecting developer name from existing stacks..."

# Get developer name from existing stack names
DEVELOPER_NAME=$(aws cloudformation list-stacks \
  --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE \
  --query 'StackSummaries[?contains(StackName, `AuthStack`)].StackName' \
  --output text | head -1 | sed 's/-AuthStack//')

if [ -z "$DEVELOPER_NAME" ]; then
  echo "❌ Error: Could not determine developer name from stacks"
  echo "   Please ensure AuthStack is deployed"
  exit 1
fi

echo "✓ Developer: $DEVELOPER_NAME"

STACK_PREFIX="${DEVELOPER_NAME}-AuthStack"

echo "→ Fetching stack outputs from $STACK_PREFIX..."

# Get outputs from CloudFormation
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_PREFIX" \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
  --output text)

API_KEY=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_PREFIX" \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiKey`].OutputValue' \
  --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_PREFIX" \
  --query 'Stacks[0].Outputs[?OutputKey==`AuthUserPoolIdC0605E59`].OutputValue' \
  --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_PREFIX" \
  --query 'Stacks[0].Outputs[?OutputKey==`AuthUserPoolClientId8216BF9A`].OutputValue' \
  --output text)

# Validate outputs
if [ -z "$API_URL" ] || [ -z "$API_KEY" ] || [ -z "$USER_POOL_ID" ] || [ -z "$USER_POOL_CLIENT_ID" ]; then
  echo "❌ Error: Could not fetch all required outputs"
  echo "   API_URL: $API_URL"
  echo "   API_KEY: $API_KEY"
  echo "   USER_POOL_ID: $USER_POOL_ID"
  echo "   USER_POOL_CLIENT_ID: $USER_POOL_CLIENT_ID"
  exit 1
fi

echo "✓ Fetched outputs"
echo ""

# Update infra/.env
INFRA_ENV_FILE="$INFRA_DIR/.env"
echo "→ Updating $INFRA_ENV_FILE..."

cat > "$INFRA_ENV_FILE" << EOF
# Auto-generated by update-env.sh - DO NOT EDIT MANUALLY
# Last updated: $(date)

# AWS Configuration
AWS_REGION=us-east-1

# Cognito User Pool
USER_POOL_ID=$USER_POOL_ID

# AppSync API
APPSYNC_URL=$API_URL
API_KEY=$API_KEY
EOF

echo "✓ Updated infra/.env"
echo ""

# Update client/.env.local
CLIENT_ENV_FILE="$CLIENT_DIR/.env.local"
echo "→ Updating $CLIENT_ENV_FILE..."

cat > "$CLIENT_ENV_FILE" << EOF
# Auto-generated by update-env.sh - DO NOT EDIT MANUALLY
# Last updated: $(date)

# AppSync GraphQL API
EXPO_PUBLIC_APPSYNC_URL=$API_URL
EXPO_PUBLIC_API_KEY=$API_KEY

# Cognito Authentication
EXPO_PUBLIC_USER_POOL_ID=$USER_POOL_ID
EXPO_PUBLIC_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID

# Test User Credentials (for development only)
COGNITO_TEST_EMAIL=test-user-1@neighborly.local
COGNITO_TEST_PASSWORD=Password123!
EOF

echo "✓ Updated client/.env.local"
echo ""

echo "=========================================="
echo "✅ Environment variables updated!"
echo "=========================================="
echo ""
echo "Updated files:"
echo "  - $INFRA_ENV_FILE"
echo "  - $CLIENT_ENV_FILE"
echo ""
echo "Configuration:"
echo "  API URL: $API_URL"
echo "  User Pool ID: $USER_POOL_ID"
echo ""
echo "⚠️  Restart your development server to apply changes:"
echo "  cd client && npm run web"
